### ISSUE TITLE
We run `bundle install` twice

### ISSUE THREAD

**Issue by nickjer** [AweSim-OSC/rails-application-template#10]
We explicitly call in the template

```ruby
run "bundle install --local"
```

which I am fine with. But by default the Rails setup will call `bundle install` at the very end. This doesn't hurt anything, but can be confusing and fills up the screen with useless information (as this information is just a repeat from earlier).

This can be fixed by documenting the use of

```shell
$ rails new <project> -m /path/to/template.rb --skip-bundle
```

or overriding the `run_bundle` method in the template:

```ruby
def run_bundle
end
```

**Comment by ericfranz** [comment]
No longer running bundle install in rails application template.
