### ISSUE TITLE
Merge this into `awesim-cli`?

### ISSUE THREAD

**Issue by nickjer** [AweSim-OSC/rails-application-template#16]
Should this be merged into the `awesim-cli` repo? This would simplify the installation of new apps and guarantee the use of our approved Rails version (even if we install later Rails versions).

For example

```shell
awesim new myapp [--skip-bundle-local/--without-skip-bundle-local]
```

This would setup using Rails v4.0.0 even if we have Rails v4.2.0 installed. This would give us time to update the scaffolding in `osc_machete_rails` and the template/assets in `awesim-rails-template` to take into account all the new changes in Rails v4.2.0 (for example, turn off Spring which causes issues on our system).

A guess on how this could be done in `awesim-cli` is adding to the `awesim.gemspec`

```ruby
spec.add_dependency "rails", "~> 4.0.0"
```

And creating a Thor class that inherits from the Rails thor class that create new apps...

```ruby
require '...'

module AweSim
  class AppGenerator < Rails::Generators::AppGenerator
  end
end
```

**Comment by ericfranz** [comment]
This was actually done for the old version. The new version will not have this done.
