### ISSUE TITLE
Enhance 'getting started' text

### ISSUE THREAD

**Issue by brianmcmichael** [AweSim-OSC/rails-application-template#19]
The initial screen is somewhat terse. This can probably be enhanced, specifically with regard to 

````
3. change the root to point to your model's index action by modifying
 public/.htaccess.passenger_fix and public/.htaccess
````

This should probably be expanded to say why we're doing this since it's not part of a traditional railsy workflow.

![initialload](https://cloud.githubusercontent.com/assets/2374718/12684874/08249ca4-c68f-11e5-8a99-d574d19bdaa6.png)

**Comment by ericfranz** [comment]
Opened separate issue. https://github.com/OSC/ood_appkit/issues/29
