### ISSUE TITLE
Update to use ood_appkit gem instead of awesim_rails

### ISSUE THREAD

**Issue by nickjer** [AweSim-OSC/rails-application-template#25]
This requires an update to take advantage of the `ood_appkit` gem:

  - `application.css.scss` needs new styles
  - `application.html.erb` needs to be "templatized" and autofill in `app_title` with string and breadcrumbs filled in (remove footer with copyright)
  - `awesim_rails.rb` replaced with `ood_appkit.rb`
  - `paperclip.rb` replace `AwesimRails.dataroot` with `OodAppkit.dataroot`
  - `favicon.ico` removed and replace link in layout with `<%= favicon_link_tag nil, href: OodAppkit.public.url.join('favicon.ico') %>`
  - `.env.development` change `RAILS_DATAROOT` to `OOD_DATAROOT`
  - `.htaccess.*` remove
  - `awesim.rb` update gems, ...

**Comment by ericfranz** [comment]
https://github.com/AweSim-OSC/rails-application-template/pull/27
