### ISSUE TITLE
Remove pages stylesheet

### ISSUE THREAD

**Issue by nickjer** [AweSim-OSC/rails-application-template#29]
Seems we forgot to remove the `pages` stylesheet definition:

![image](https://cloud.githubusercontent.com/assets/4260509/20673618/d0a5f246-b553-11e6-80a6-2922c9ba11aa.png)

**Comment by brianmcmichael** [comment]
Is this in CFS or the RAT?

**Comment by nickjer** [comment]
RAT

**Comment by brianmcmichael** [comment]
Done at 6666c2913b63bad9ab0d304a7672c76376b0cd3a
