### ISSUE TITLE
Is ood_support necessary?

### ISSUE THREAD

**Issue by nickjer** [AweSim-OSC/rails-application-template#30]
This is a question in regards to:

https://github.com/AweSim-OSC/rails-application-template/blob/9bce52a9617a9aa840dde973cc5f707b43326bbe/awesim.rb#L33

Do we explicitly use this gem in a new Rails app? I was unable to find any code in this Rails Template that uses it. If it is only used as a dependency of another gem, then maybe we should let that gem handle it instead.

**Comment by ericfranz** [comment]
I'm in favor of removing this. ood_support is a useful gem and we will probably add more stuff to it; but its a dependency of ood_appkit and we include ood_appkit. Similar to using active support in rails but just including rails in the gemfile.

**Comment by brianmcmichael** [comment]
I'm not sure why exactly I added this, other than that it was a new set of tools. I can pull it back out and see what happens.

**Comment by nickjer** [comment]
Since you took the initiative in the reply, I am assigning it to you @brianmcmichael
